### ISSUE TITLE
Chapter 6. 카프카 운영 가이드

### ISSUE THREAD

**Issue by kmg28801** [kmg28801/kafka-study#6]

**Comment by kmg28801** [comment]
> 들어가기 전에.. 저는 모든 실습을 컨테이너 환경에서 진행하였습니다.

# 필수 카프카 명령어 

- 토픽을 생성하기 위해 카프카에서 제공해주는 명령어는 `kafka-topics.sh`

```cmd
# 카프카 토픽 생성 명령어 
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --topic peter-topic --create --replication-factor 1 --partitions 1
Created topic peter-topic.
# 카프카 토픽 조회 명령어
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --list
peter-topic
# 카프카 토픽 상세 정보 조회 명령어
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --topic peter-topic --describe
Topic: peter-topic	TopicId: twtcaEsNRDCzaIkBvvRsXw	PartitionCount: 1	ReplicationFactor: 1	Configs:
	Topic: peter-topic	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
```

- 카프카 토픽 상세 정보 조회 명령어 분석

```
Topic: peter-topic	TopicId: twtcaEsNRDCzaIkBvvRsXw	PartitionCount: 1	ReplicationFactor: 1	Configs:
	Topic: peter-topic	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
```
- 첫 줄에는 토픽에 대한 기본 정보 노출
- 다음 줄 부터는 각 파티션에 대한 기본 정보 노출

# 토픽 설정 변경 (중요)

- 카프카 운영 중 브로커의 디스크 사용량이 높아지는 경우, 안정적인 운영을 위해 보통 디스크 공간을 가장 많이 차지하는 토픽의 보관 주기를 줄여주는 게 가장 좋은 방법
- 보관 주기에 관한 별도의 옵션을 주지 않고, 브로커의 기본 설정값을 유지한 상태에서 토픽을 생성했다면 해당 토픽의 보관주기는 `7일`
- 토픽의 보관주기 설정을 변경하기 위해 `kafka-configs.sh` 명령어를 사용
- `alter` 옵션을 추가하고, `entity-type`에 `topics`를 추가 `entity-name`에는 토픽의 이름 `add-config` 옵션에 보관주기 1시간을 의미하는 `retention.ms=3600000` 설정
```cmd
# 설정 변경 명령어
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-configs.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --alter --entity-type topics --entity-name peter-topic --add-config retention.ms=3600000
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
Completed updating config for entity: topic 'peter-topic'.

# 잘 적용되었는지 확인하는 명령어
root@18ed8f2bfb8d:/opt/kafka/bin#  kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --topic peter-topic --describe
Topic: peter-topic	TopicId: twtcaEsNRDCzaIkBvvRsXw	PartitionCount: 1	ReplicationFactor: 1	Configs: retention.ms=3600000
	Topic: peter-topic	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
```

- 만약 추가 옵션으로 설정한 보관주기 1시간 설정을 삭제하고 싶은 경우 `delete-config`를 추가하고 삭제할 옵션인 `retention.ms`를 입력하면 된다.

```cmd
# config 삭제
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-configs.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --alter --entity-type topics --entity-name peter-topic --delete-config retention.ms
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
Completed updating config for entity: topic 'peter-topic'.
# 조회
root@18ed8f2bfb8d:/opt/kafka/bin#  kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --topic peter-topic --describe
Topic: peter-topic	TopicId: twtcaEsNRDCzaIkBvvRsXw	PartitionCount: 1	ReplicationFactor: 1	Configs:
	Topic: peter-topic	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
```


# 토픽의 파티션 수 변경

- 카프카에서는 토픽의 파티션 수는 **증가만 가능하고, 감소는 불가능**
- 처음 토픽을 생성할 때 파티션 수를 처리량에 대해 미리 확인한 후 신중하게 결정해 적용이 필요
- 정확한 판단이 어렵다면, 가능한 작은 수의 파티션으로 우선 생성해두고, 필요한 경우에 파티션 수를 늘려주는 방법으로 대응
- 파티션만 증가했다고 메세지에 대한 전체 처리 성능이 좋아지는 것은 아님, 파티션의 수만큼 **컨슈머 역시 추가가 필요**
- 토픽의 파티션 수를 변경하기 위한 명령어는 `kafka-topics.sh`, 파티션 수 변경을 위해서 `alter` 옵션 추가

```cmd
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --alter --topic peter-topic --partitions 2
WARNING: If partitions are increased for a topic that has a key, the partition logic or ordering of the messages will be affected
Adding partitions succeeded!
```

- 파티션을 늘리면 메시지 순서에 영향을 끼칠 수 있다는 주의 문구가 나타나고, 파티션 수가 성공적으로 늘어났다는 내용이 위 명령어에 노출

- 파티션을 늘리면 메시지 순서에 영향을 끼칠 수 있다는 주의 문구에 대한 테스트 
  - 파티션 수가 1인 토픽 peter-test 생성
  - 프로듀서가 key를 이용해 peter-test 토픽에 메시지 전송
  - 컨슈머가 peter-test 토픽에서 메시지를 가져와서 결과 확인
  - 토픽 peter-test의 파티션 수를 1에서 4로 변경
  - 프로듀서가 key를 이용해 peter-test 토픽에 메시지를 전송
  - 컨슈머가 peter-test 토픽에서 메시지를 가져와 결과 확인


> 위 프로세스에 대한 순차적인 실습은 아래를 따라하시면 됩니다.

```cmd
# 토픽 생성
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --topic peter-test --create --replication-factor 1 --partitions 1
Created topic peter-test.

# 메시지 프로듀싱
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-console-producer.sh --topic peter-test --broker-list kafka1:9092,kafka2:9092,kafka3:9092
>a
>b
>c
>

# 메시지 컨슈밍
 user  ~/Desktop/kafka/kafka  docker-compose exec kafka1 /bin/bash
root@18ed8f2bfb8d:/# cd opt
root@18ed8f2bfb8d:/opt# cd kafka
root@18ed8f2bfb8d:/opt/kafka# cd bin
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-console-consumer.sh --topic peter-test --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092
a
b
c
```
> 여기서 삽질한 내용 공유드립니다. 저는 기존에는 집에서만 실습을 진행했는데, 카페에서 실습하다보니 Local PC IP가 바뀌는 현상이 발생했습니다. 이때는 꼭 hosts 파일에서 IP를 수정해줘야, 스프링 애플리케이션에서 카프카 컨테이너에 정상 접근이 됩니다.https://github.com/kmg28801/kafka-study/issues/4#issuecomment-1529604700


- 스프링 애플리케이션에서 컨슈밍한 결과
```cmd
Topic: peter-test, Partition: 0, Offset: 14, Key: 1, Value: e140
Topic: peter-test, Partition: 0, Offset: 15, Key: 2, Value: e141
Topic: peter-test, Partition: 0, Offset: 16, Key: 1, Value: e142
Topic: peter-test, Partition: 0, Offset: 17, Key: 2, Value: e143
Topic: peter-test, Partition: 0, Offset: 18, Key: 1, Value: e144
Topic: peter-test, Partition: 0, Offset: 19, Key: 2, Value: e145
Topic: peter-test, Partition: 0, Offset: 20, Key: 1, Value: e146
Topic: peter-test, Partition: 0, Offset: 21, Key: 2, Value: e147
Topic: peter-test, Partition: 0, Offset: 22, Key: 1, Value: e148
Topic: peter-test, Partition: 0, Offset: 23, Key: 2, Value: e149
```

- 파티션 증설
```cmd
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --alter --topic peter-test --partitions 4
WARNING: If partitions are increased for a topic that has a key, the partition logic or ordering of the messages will be affected
Adding partitions succeeded!
```


```
Produce message : taejoong
Topic: peter-test, Partition: 0, Offset: 59, Key: 2, Value: taejoong1
Topic: peter-test, Partition: 0, Offset: 60, Key: 2, Value: taejoong3
Topic: peter-test, Partition: 0, Offset: 61, Key: 2, Value: taejoong5
Topic: peter-test, Partition: 0, Offset: 62, Key: 2, Value: taejoong7
Topic: peter-test, Partition: 0, Offset: 63, Key: 2, Value: taejoong9
Topic: peter-test, Partition: 3, Offset: 15, Key: 1, Value: taejoong0
Topic: peter-test, Partition: 3, Offset: 16, Key: 1, Value: taejoong2
Topic: peter-test, Partition: 3, Offset: 17, Key: 1, Value: taejoong4
Topic: peter-test, Partition: 3, Offset: 18, Key: 1, Value: taejoong6
Topic: peter-test, Partition: 3, Offset: 19, Key: 1, Value: taejoong8
```

- 위 결과처럼 key:2인 경우 파티션 0번에서만 메시지를 가져오고, key:1인 경우는 파티션 3번엥서만 메시지를 컨슈밍하는 것을 확인 할 수 있다.
- 이 경우 key=1의 메시지를 필요로 하는 컨슈머가 파티션 수 변경 이후에도 계속해서 0번 파티션만 바라본다면, 컨슈머는 더 이상 메시지를 가져갈 수 없는 문제가 발생
- 즉 key를 이용해 메시지를 전송하고, 가져오는 형태로 운영된다면, 파티션 수를 변경할 때 주의가 필요하다.


# 토픽의 리플리케이션 팩터 변경

- 파티션 정보 확인
```json
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --topic peter-topic --describe
Topic: peter-topic	TopicId: 8Bm3oe9VR1Sd9xE-r0pi2Q	PartitionCount: 2	ReplicationFactor: 1	Configs:
	Topic: peter-topic	Partition: 0	Leader: 2	Replicas: 2	Isr: 2
	Topic: peter-topic	Partition: 1	Leader: 3	Replicas: 3	Isr: 3
```

- 리플리케이션 팩터 변경을 위한 Json 생성
> 컨테이너에 vi, vim 없는 경우 apt-get update, apt-get install vim 실행
```json
{"version":1,
"partitions":[
                     {"topic":"peter-topic","partition":0,"replicas"[2,3]},
                     {"topic":"peter-topic","partition":1,"replicas"[3,1]}
]}

```

- 위 json 파일 설명
  - 파티션 0번은 replicas [2,3]으로 설정하였는데 맨 처음 숫자가 리더가 존재하는 브로커 ID입니다. 저의 경우 리더는 브로커2, 리플리카는 브로커3으로 설정하였습니다.
  - 여기서 주의할 점으로는, replicas의 첫 번째 숫자를 현재 상태의 토픽 파티션 정보를 확인한 후 각 파티션의 현재 리더 정보와 일치하도록 설정해 파티션의 리더가 변경되지 않게 해야 한다는 점입니다.
  - 리더가 변경되지 않기 때문에 토픽의 리플리케이션 팩터를 변경해도 프로듀 서와 컨슈머에 영향을 주지 않을 수 있습니다.
  - 토픽의 리플리케이션 팩터를 2가 아닌 3으로 설정하기를 원한다면, replicas 설정에 숫자를 하나 더 추가하면 됩니다.

- 토픽의 리플리케이션 팩터를 변경하는 카프카 명령어는 `kafka-reassign-partitions.sh`
- 추가 옵션으로는 `reassignment-json-file` 옵션에 미리 만들어둔 json 형식의 파일 경로와 파일명을 입력 후 `execute`로 실행
```cmd
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-reassign-partitions.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --reassignment-json-file rf.json --execute
Warning: --zookeeper is deprecated, and will be removed in a future version of Kafka.
Current partition replica assignment

{"version":1,"partitions":[{"topic":"peter-topic","partition":0,"replicas":[2],"log_dirs":["any"]},{"topic":"peter-topic","partition":1,"replicas":[3],"log_dirs":["any"]}]}

Save this to use as the --reassignment-json-file option during rollback
Successfully started partition reassignments for peter-topic-0,peter-topic-1

# 결과 확인
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-topics.sh --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 --topic peter-topic --describe
Topic: peter-topic	TopicId: 8Bm3oe9VR1Sd9xE-r0pi2Q	PartitionCount: 2	ReplicationFactor: 2	Configs:
	Topic: peter-topic	Partition: 0	Leader: 2	Replicas: 2,3	Isr: 2,3
	Topic: peter-topic	Partition: 1	Leader: 3	Replicas: 3,1	Isr: 3,1
```



# 컨슈머 그룹 리스트 확인


- 컨슈머는 오프셋의 저장방식에 따라 오프셋을 주키퍼에 저장하는 방식인 올드 컨슈머, 오프셋을 카프카의 토픽으로 저장하는 뉴 컨슈머 두 가지가 존재
- 카프카 토픽 기반의 뉴 컨슈머 그룹을 확인하려면 추가 옵션으로 `bootstrap-server`와 브로커 리스트 입력 필요
- 컨슈머 그룹 리스트를 보기 위한 명령어는 `kafka-consumer-groups.sh`, 추가 옵션으로 `bootstrap-server` 옵션으로 브로커 리스트를 입력하고, `list` 옵션을 준 다음 실행

- 저는 스프링 부트로 실습을 진행해서 교재와는 달리 컨슈머 그룹이 존재했습니다. (이미 스프링부트로 실습을 전부 진행했기에 파이썬은 무시하였습니다.)
```cmd
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-consumer-groups.sh --bootstrap-server kafka1:9092,kafka2:9093,kafka3:9094 --list
peter-test
peter-test-consumer-group
peter-topic
```

- 컨슈머 상태와 오프셋 확인은 `kafka-consumer-groups.sh`이며 추가 옵션으로는 `bootstrap-server` 옵션으로 브로커 리스트를 입력하고, `group` 옵션으로 컨슈머 그룹 이름을 준 다음 `describe` 명령어 실행
```cmd
root@18ed8f2bfb8d:/opt/kafka/bin# kafka-consumer-groups.sh --bootstrap-server kafka1:9092,kafka2:9093,kafka3:9094 --group peter-topic --describe

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                 HOST            CLIENT-ID
peter-topic     peter-topic     0          5               5               0               consumer-peter-topic-1-570089fb-7039-4363-8005-2b22a11f3ce6 /172.19.0.1     consumer-peter-topic-1
peter-topic     peter-topic     1          5               5               0               consumer-peter-topic-1-570089fb-7039-4363-8005-2b22a11f3ce6 /172.19.0.1     consumer-peter-topic-1
```

- LAG은 현재 토픽의 저장된 메시지와 컨슈머가 가져간 메시지의 차이를 의미
- 아래 그림을 보면 프로듀서가 10개의 메시지를 카프카로 보냈고, 컨슈머가 모든 메시지를 가져갔다면, 컨슈머는 카프카에서 더 이상 가져갈 메시지가 없고 이런 상태를 LAG = 0이라고 한다.
- LAG 숫자가 높다는 것은 해당 토픽 또는 파티션에 컨슈머가 읽어가지 못한 메시지가 많이 있다는 의미
- LAG이 계속 증가하는 상황이라면 컨슈머 처리가 늦어지고 있는 것이기 때문에 컨슈머나 파티션 수를 늘려서 대응을 해야 하며, 특정 파티션에서만 LAG이 증가한다면 해당 파티션에 연결된 컨슈머를 체크해야 한다.
<img width="1335" alt="image" src="https://github.com/kmg28801/kafka-study/assets/53685313/16615ebe-546a-4da7-aa0d-41fcd066e96e">

# 주키퍼 스케일 아웃


```yaml
version: '3.7'
services: 

  zk1:
    container_name: zookeeper1
    image: wurstmeister/zookeeper:latest
    restart: always
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk1/data:/data"

  zk2:
    container_name: zookeeper2
    image: wurstmeister/zookeeper:latest
    restart: always
    hostname: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk2/data:/data"

  zk3:
    container_name: zookeeper3
    image: wurstmeister/zookeeper:latest
    restart: always
    hostname: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk3/data:/data"
      
  zk4:
    container_name: zookeeper4
    image: wurstmeister/zookeeper:latest
    restart: always
    hostname: zk4
    ports:
      - "2184:2181"
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk4/data:/data"
      
  zk5:
    container_name: zookeeper5
    image: wurstmeister/zookeeper:latest
    restart: always
    hostname: zk5
    ports:
      - "2185:2181"
    environment:
      ZOO_MY_ID: 5
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk5/data:/data"   

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:latest
    restart: on-failure
    depends_on:
      - zk1
      - zk2
      - zk3
      - zk4
      - zk5
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      BOOTSTRAP_SERVERS: host.docker.internal:9092, host.docker.internal:9093, host.docker.internal:9094
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2182,zk3:2183,zk4:2184,zk5:2185"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:latest
    restart: on-failure
    depends_on:
      - zk1
      - zk2
      - zk3
      - zk4
      - zk5
    ports:
      - "9093:9092"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      BOOTSTRAP_SERVERS: host.docker.internal:9092, host.docker.internal:9093, host.docker.internal:9094
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2182,zk3:2183,zk4:2184,zk5:2185"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka3:
    container_name: kafka3
    image: wurstmeister/kafka:latest
    restart: on-failure
    depends_on:
      - zk1
      - zk2
      - zk3
      - zk4
      - zk5
    ports:
      - "9094:9092"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      BOOTSTRAP_SERVERS: host.docker.internal:9092, host.docker.internal:9093, host.docker.internal:9094
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2182,zk3:2183,zk4:2184,zk5:2185"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "10000:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.docker.internal:9092,host.docker.internal:9093,host.docker.internal:9094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zk1:2181,zk2:2182,zk3:2183,zk4:2184,zk5:2185
      
```

- 토픽 생성
```cmd
root@3fd07054b29e:/opt/kafka/bin# kafka-topics.sh --create --topic peter5 --replication-factor 2 --partitions 5 --zookeeper zookeeper1:2181,zookeeper2:2182,zookeeper3:2183,zookeeper4:2184,zookeeper5:2185
Created topic peter5.
```
# 카프카 JMX 설정 방법

- JMX는 자바로 만든 애플리케이션의 모ㅠ니터링 등을 위한 도구를 제공하는 자바 API로, MBean이라는 객체로 표현
- JMX를 사용할 수 있도록 설정하는 방법은, 카프카 실행 파일에 JMX 관련 설정을 추가하는 방법과, systemd를 이용한 환경변수 추가 방법이 있는데 저는 docker-compose에 환경변수 추가로 작업하였습니다.


- docker-compose 아래만 수정
```yaml
kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:latest
    restart: on-failure
    depends_on:
      - zk1
      - zk2
      - zk3
      - zk4
      - zk5
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      BOOTSTRAP_SERVERS: host.docker.internal:9092, host.docker.internal:9093, host.docker.internal:9094
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2182,zk3:2183,zk4:2184,zk5:2185"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      JMX_PORT: 9999
```

- kafka1 컨테이너에서 9999 포트가 리슨 상태인지 확인 필요
```
root@9a8a71315a79:/# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:45813        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:43323           0.0.0.0:*               LISTEN      1/java
tcp        0      0 0.0.0.0:46113           0.0.0.0:*               LISTEN      1/java
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN      1/java
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      1/java
```



- 주요 지표
  - Message in rate
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=MessageInPerSec
    - 설명 : 브로커 서버로 초당 들어오는 메시지 수
  - Byte in rate
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec
    - 설명 : 브로커 서버로 초당 들어오는 사이즈
  - Byte out rate
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec
    - 설명 : 브로커 서버로 초당 나가는 사이즈
  - under replicated partitions
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=UnderReplicatedPartitions
    - 설명 : 현재 복제가 되지 않고 있는 파티션 수 확인, 알람을 설정한다면 브로커의 이상 유무를 빠르게 감지 가능
    - 기본값 : 0이 아닌 경우 알람 발생
  - Is Controller active on broker
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=ActiveControllerCount
    - 설명 : 클러스터 내 컨트롤러 서버를 찾는 용도로 사용. 클러스터 내 컨트롤러 서버는 1대
    - 기본값 : 컨트롤러는 1, 아닌 경우 0
  - Partition Counts
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=PartitionbCount
    - 설명 : 브로커에 있는 파티션 수를 나타냄. 특정 브로커에 너무 많은 파티션 수가 몰려있는 경우를 파악하거나 브로커에 전체 파티션 수 파악에 용이
  - Leader Counts
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=LeaderCount
    - 설명 : 브로커에 있는 리더의 수, 클러스터 내 특정 브로커에 리더가 집중되어 있으면 해당 브로커에만 부담이 크기 때문에 각각의 브로커에 골고루 리더를 분산 시켜주는 것이 좋음
  - ISR shrink rate
    - MBean 이름 : kafka.server:type=BrokerTopicMetrics,name=IsShrinksPerSec
    - 설명 : 브로커가 다운되는 경우 일부 파티션에서 ISR 축소가 발생하게 되고 해당 비율을 나타내는 지표, 알람을 설정한다면 브로커의 이상유무를 빠르게 감지 가능
    - 기본값 : 0이 아닌 경우 알람 발생


# 카프카 매니저

**Comment by kmg28801** [comment]
# 카프카 매니저 docker 구축

https://haithai91.medium.com/zookeeper-kafka-with-docker-b1d4b33c0d5e


> yaml 수정 필요


```yaml
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - ./pub-technology/zookeeper/data:/data
      - ./pub-technology/zookeeper/datalog:/datalog
  
  kafka-server-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./pub-technology/kafka1/data:/var/lib/kafka/data
  kafka-server-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./pub-technology/kafka2/data:/var/lib/kafka/data
  manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
      

```
